services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23.8.14.6
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=admin
    ports:
      - 9000:9000/tcp
    volumes:
      - ./volumes/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=1
      - GF_ORG_NAME=anonorg
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana:/var/lib/grafana
